services:
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - private
      - public
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - private
    volumes:
      - ./db/mysql:/mysql/mysql
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
  frontend:
    build:
      context: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - public
networks:
  public:
  private:
    driver: bridge
volumes:
  db-data: