-- MySQL Script generated by MySQL Workbench
-- Thu Nov  7 23:12:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
-- Base de datos de la pagina web trueque-libre

-- -----------------------------------------------------
-- Schema users
--
-- Base de datos de la pagina web trueque-libre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `users` ;

-- -----------------------------------------------------
-- Table `users`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`Roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`Users` (
  `id` VARCHAR(50) NOT NULL COMMENT 'GUID generado automaticamente por el backend',
  `userName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `state` TINYINT NULL,
  `Roles_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Users_Roles_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_Users_Roles`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `users`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`.`RoleActions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`.`RoleActions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actionName` VARCHAR(100) NOT NULL,
  `Roles_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `actionName_UNIQUE` (`actionName` ASC),
  INDEX `fk_RoleActions_Roles1_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_RoleActions_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `users`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
